// <auto-generated />
using System;
using FiapCloudGames.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FiapCloudGames.Infrastructure.Migrations
{
    [DbContext(typeof(FCGDbContext))]
    partial class FCGDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FiapCloudGames.Domain.Entities.Jogo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CadastradoEm")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descricao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Preco")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Titulo")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Jogos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CadastradoEm = new DateTime(2026, 1, 15, 0, 39, 20, 590, DateTimeKind.Local).AddTicks(1280),
                            Descricao = "RPG",
                            Preco = 249.90m,
                            Titulo = "Elden Ring"
                        },
                        new
                        {
                            Id = 2,
                            CadastradoEm = new DateTime(2026, 1, 15, 0, 39, 20, 591, DateTimeKind.Local).AddTicks(1252),
                            Descricao = "Esporte",
                            Preco = 249.90m,
                            Titulo = "EA FC 26"
                        });
                });

            modelBuilder.Entity("FiapCloudGames.Domain.Entities.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CadastradoEm")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Nivel")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Senha")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Usuarios");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CadastradoEm = new DateTime(2026, 1, 15, 3, 39, 20, 591, DateTimeKind.Utc).AddTicks(5431),
                            Email = "rafhita1@gmail.com",
                            Nivel = 2,
                            Nome = "Rafael Santos",
                            Senha = "jx2A6WDVUKiccfcAYTCJJg=="
                        },
                        new
                        {
                            Id = 2,
                            CadastradoEm = new DateTime(2026, 1, 15, 3, 39, 20, 591, DateTimeKind.Utc).AddTicks(5874),
                            Email = "admin@fcg.com",
                            Nivel = 2,
                            Nome = "Admin FCG",
                            Senha = "IuL0vUhf2mtqMeh2otN5GQ=="
                        },
                        new
                        {
                            Id = 3,
                            CadastradoEm = new DateTime(2026, 1, 15, 3, 39, 20, 591, DateTimeKind.Utc).AddTicks(5875),
                            Email = "user@fcg.com",
                            Nivel = 1,
                            Nome = "User FCG",
                            Senha = "BxZkP2nHgsa2DbpyDZLDRQ=="
                        });
                });

            modelBuilder.Entity("FiapCloudGames.Domain.Entities.UsuarioJogo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AdiquiridoEm")
                        .HasColumnType("datetime2");

                    b.Property<int>("JogoId")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("JogoId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("UsuarioJogos");
                });

            modelBuilder.Entity("FiapCloudGames.Domain.Entities.UsuarioJogo", b =>
                {
                    b.HasOne("FiapCloudGames.Domain.Entities.Jogo", null)
                        .WithMany()
                        .HasForeignKey("JogoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FiapCloudGames.Domain.Entities.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
